version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Descomente as linhas abaixo se você tiver variáveis de ambiente
    env_file:
      - .env.local
    restart: unless-stopped

  # Adicione outros serviços conforme necessário (banco de dados, redis, etc.)
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: booking_db
  #     POSTGRES_USER: booking_user
  #     POSTGRES_PASSWORD: booking_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:
